const { createClient } = supabase;
const sb = createClient(window.MOHIT_CONFIG.SUPABASE_URL, window.MOHIT_CONFIG.SUPABASE_PUBLISHABLE_KEY);
let jobs=[], videos=[], photos=[], content={};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function note(id,text,error=false){const el=$(id);if(!el)return;el.textContent=text;el.className=error?'notice error':'notice';}
function setStatus(text,error=false){note('status',text,error)}
async function guard(){try{
  if(!window.MOHIT_CONFIG?.SUPABASE_URL||!window.MOHIT_CONFIG?.SUPABASE_PUBLISHABLE_KEY) throw new Error('Supabase configuration is missing.');
  const {data:sd,error:se}=await sb.auth.getSession(); if(se)throw se;
  if(!sd?.session?.user){setStatus('Please login first. Redirecting to Login…',true);setTimeout(()=>location.href='login.html?next=admin.html',700);return;}
  const {data:ud,error:ue}=await sb.auth.getUser();if(ue)throw ue;const user=ud?.user;if(!user)throw new Error('Login session expired.');
  const {data:p,error:pe}=await sb.from('profiles').select('role,full_name').eq('id',user.id).maybeSingle();if(pe)throw pe;
  if(p?.role!=='admin'){setStatus('Access denied. Your account is not an admin.',true);return;}
  setStatus(`Admin access granted${p.full_name?' — '+p.full_name:''}.`);$('adminArea').style.display='block';
  await Promise.all([loadJobs(),loadContent(),loadVideos(),loadPhotos()]);
}catch(e){console.error(e);setStatus('Admin check failed: '+(e.message||e),true)}}
async function loadJobs(){const {data,error}=await sb.from('jobs').select('*').order('created_at',{ascending:false});if(error)return note('msg',error.message,true);jobs=data||[];$('count').textContent=jobs.length+' listings';$('rows').innerHTML=jobs.length?jobs.map(j=>`<tr><td>${esc(j.title)}</td><td>${esc(j.company)}</td><td>${esc(j.category)}</td><td>${j.is_active?'🟢 Active':'⚪ Hidden'}</td><td><button class="btn small ghost" onclick="editJob('${j.id}')">Edit</button> <button class="btn small ghost" onclick="delJob('${j.id}')">Delete</button></td></tr>`).join(''):'<tr><td colspan="5">No jobs yet.</td></tr>'}
function resetJob(){$('jobForm').reset();$('jobId').value='';$('formTitle').textContent='Add Job';$('is_active').checked=true}
window.editJob=id=>{const j=jobs.find(x=>x.id===id);if(!j)return;['title','company','location','category','job_type','experience','salary','skills','description','apply_url'].forEach(k=>$(k).value=j[k]||'');$('jobId').value=id;$('is_remote').checked=!!j.is_remote;$('is_active').checked=!!j.is_active;$('formTitle').textContent='Edit Job';showTab('jobsTab');scrollTo({top:0,behavior:'smooth'})}
$('jobForm').onsubmit=async e=>{e.preventDefault();try{const {data:{user}}=await sb.auth.getUser();if(!user)return note('msg','Please login again.',true);const payload={title:$('title').value.trim(),company:$('company').value.trim(),location:$('location').value.trim(),category:$('category').value,job_type:$('job_type').value.trim(),experience:$('experience').value.trim(),salary:$('salary').value.trim(),skills:$('skills').value.trim(),description:$('description').value.trim(),apply_url:$('apply_url').value.trim(),is_remote:$('is_remote').checked,is_active:$('is_active').checked,created_by:user.id};const id=$('jobId').value;const res=id?await sb.from('jobs').update(payload).eq('id',id):await sb.from('jobs').insert(payload);if(res.error)throw res.error;note('msg','Job saved successfully.');resetJob();await loadJobs()}catch(e){note('msg',e.message||String(e),true)}};
$('reset').onclick=resetJob;
window.delJob=async id=>{if(!confirm('Delete this job?'))return;const {error}=await sb.from('jobs').delete().eq('id',id);if(error)return note('msg',error.message,true);await loadJobs()};
async function loadContent(){const {data,error}=await sb.from('site_content').select('*');if(error)return note('contentMsg',error.message,true);content=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));['site_name','hero_eyebrow','hero_title','hero_text','career_title','career_text','about_title','about_text','contact_text','youtube_section_title','photos_section_title'].forEach(k=>{if($('c_'+k))$('c_'+k).value=content[k]||''})}
$('contentForm').onsubmit=async e=>{e.preventDefault();try{const {data:{user}}=await sb.auth.getUser();const keys=['site_name','hero_eyebrow','hero_title','hero_text','career_title','career_text','about_title','about_text','contact_text','youtube_section_title','photos_section_title'];const rows=keys.map(k=>({key:k,value:$('c_'+k).value.trim(),updated_by:user.id,updated_at:new Date().toISOString()}));const {error}=await sb.from('site_content').upsert(rows);if(error)throw error;note('contentMsg','Website content saved successfully.')}catch(e){note('contentMsg',e.message||String(e),true)}};
function extractYoutubeId(url){try{const u=new URL(url.trim());if(u.hostname==='youtu.be')return u.pathname.slice(1).split('/')[0];if(u.searchParams.get('v'))return u.searchParams.get('v');const m=u.pathname.match(/\/(?:embed|shorts)\/([^/?]+)/);return m?m[1]:''}catch{return ''}}
function youtubeThumb(id){return id?`https://img.youtube.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`:''}
async function loadVideos(){const {data,error}=await sb.from('site_videos').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error)return note('videoMsg',error.message,true);videos=data||[];$('videoCount').textContent=videos.length+' videos';$('videoRows').innerHTML=videos.length?videos.map(v=>{const id=extractYoutubeId(v.youtube_url);return `<div class="list-item"><div class="video-mini">${id?`<img src="${youtubeThumb(id)}" alt="">`:'▶️'}</div><div class="grow"><b>${esc(v.title)}</b><div class="muted">${v.is_active?'🟢 Published':'⚪ Hidden'} · Order ${v.sort_order}</div></div><button class="btn small ghost" onclick="editVideo('${v.id}')">Edit</button><button class="btn small ghost" onclick="delVideo('${v.id}')">Delete</button></div>`}).join(''):'<div class="muted">No YouTube videos added yet.</div>'}
function resetVideo(){$('videoForm').reset();$('videoId').value='';$('videoFormTitle').textContent='Add YouTube Video';$('videoActive').checked=true;$('videoOrder').value=0}
window.editVideo=id=>{const v=videos.find(x=>x.id===id);if(!v)return;$('videoId').value=id;$('videoTitle').value=v.title||'';$('youtubeUrl').value=v.youtube_url||'';$('videoDescription').value=v.description||'';$('videoOrder').value=v.sort_order||0;$('videoActive').checked=!!v.is_active;$('videoFormTitle').textContent='Edit YouTube Video';showTab('videosTab');scrollTo({top:0,behavior:'smooth'})}
$('videoForm').onsubmit=async e=>{e.preventDefault();try{const {data:{user}}=await sb.auth.getUser();const url=$('youtubeUrl').value.trim();if(!extractYoutubeId(url))return note('videoMsg','Please enter a valid YouTube watch, youtu.be, shorts or embed link.',true);const payload={title:$('videoTitle').value.trim(),youtube_url:url,description:$('videoDescription').value.trim(),thumbnail_url:youtubeThumb(extractYoutubeId(url)),sort_order:Number($('videoOrder').value||0),is_active:$('videoActive').checked,created_by:user.id,updated_at:new Date().toISOString()};const id=$('videoId').value;const res=id?await sb.from('site_videos').update(payload).eq('id',id):await sb.from('site_videos').insert(payload);if(res.error)throw res.error;note('videoMsg','YouTube video saved.');resetVideo();await loadVideos()}catch(e){note('videoMsg',e.message||String(e),true)}};
$('videoReset').onclick=resetVideo;
window.delVideo=async id=>{if(!confirm('Delete this YouTube video?'))return;const {error}=await sb.from('site_videos').delete().eq('id',id);if(error)return note('videoMsg',error.message,true);await loadVideos()};
function safeFileName(name){return name.toLowerCase().replace(/[^a-z0-9.\-_]+/g,'-').replace(/-+/g,'-').slice(-100)}
$('photoFile').onchange=()=>{const f=$('photoFile').files[0];if(!f){$('photoPreview').innerHTML='';return}if(f.size>6*1024*1024){note('photoMsg','Photo is larger than 6 MB. Please compress it first.',true);return}$('photoPreview').innerHTML=`<img src="${URL.createObjectURL(f)}" alt="Preview">`}
async function loadPhotos(){const {data,error}=await sb.from('site_photos').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error)return note('photoMsg',error.message,true);photos=data||[];$('photoCount').textContent=photos.length+' photos';$('photoRows').innerHTML=photos.length?photos.map(p=>`<div class="media-card"><img src="${esc(p.image_url)}" alt="${esc(p.alt_text||p.title||'Website photo')}"><div class="media-body"><b>${esc(p.title||'Untitled photo')}</b><div class="muted">${p.is_active?'🟢 Published':'⚪ Hidden'} · Order ${p.sort_order}</div><button class="btn small ghost" onclick="delPhoto('${p.id}')">Delete</button></div></div>`).join(''):'<div class="muted">No photos uploaded yet.</div>'}
$('photoForm').onsubmit=async e=>{e.preventDefault();try{const {data:{user}}=await sb.auth.getUser();const f=$('photoFile').files[0];if(!f)return note('photoMsg','Choose a photo first.',true);if(f.size>6*1024*1024)return note('photoMsg','Photo must be 6 MB or smaller.',true);const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`website/${crypto.randomUUID()}-${safeFileName(f.name.replace(/\.[^.]+$/,''))}.${ext}`;note('photoMsg','Uploading photo…');const up=await sb.storage.from('site-media').upload(path,f,{contentType:f.type,upsert:false});if(up.error)throw up.error;const {data:pub}=sb.storage.from('site-media').getPublicUrl(path);const {error}=await sb.from('site_photos').insert({title:$('photoTitle').value.trim(),image_url:pub.publicUrl,storage_path:path,alt_text:$('photoAlt').value.trim(),sort_order:Number($('photoOrder').value||0),is_active:$('photoActive').checked,created_by:user.id});if(error){await sb.storage.from('site-media').remove([path]);throw error}note('photoMsg','Photo uploaded successfully.');$('photoForm').reset();$('photoActive').checked=true;$('photoOrder').value=0;$('photoPreview').innerHTML='';await loadPhotos()}catch(e){note('photoMsg',e.message||String(e),true)}};
window.delPhoto=async id=>{if(!confirm('Delete this website photo?'))return;const p=photos.find(x=>x.id===id);const {error}=await sb.from('site_photos').delete().eq('id',id);if(error)return note('photoMsg',error.message,true);if(p?.storage_path)await sb.storage.from('site-media').remove([p.storage_path]);await loadPhotos()};
function showTab(id){document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab-btn').forEach(x=>x.classList.toggle('active',x.dataset.tab===id))}
document.querySelectorAll('.tab-btn').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('logout').onclick=async()=>{await sb.auth.signOut();location.href='index.html'};
guard();
